name: Auto-create Issue on Workflow Failure

on:
  workflow_run:
    workflows: ["Metrics", "CodeQL", "Deploy Jekyll with GitHub Pages dependencies preinstalled"]
    types:
      - completed

jobs:
  create-issue-on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create issue on workflow failure
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const workflowName = '${{ github.event.workflow_run.name }}';
            const workflowUrl = '${{ github.event.workflow_run.html_url }}';
            const runId = '${{ github.event.workflow_run.id }}';
            const headSha = '${{ github.event.workflow_run.head_sha }}';
            const headBranch = '${{ github.event.workflow_run.head_branch }}';
            const runAttempt = '${{ github.event.workflow_run.run_attempt }}';
            const runStarted = '${{ github.event.workflow_run.run_started_at }}';
            
            // Check if an issue already exists for this workflow failure
            const existingIssues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'automated-issue,workflow-failure',
              per_page: 100
            });
            
            const issueTitle = `🚨 Workflow Failure: ${workflowName}`;
            const duplicateIssue = existingIssues.data.find(issue => 
              issue.title === issueTitle && 
              issue.body.includes(runId)
            );
            
            if (duplicateIssue) {
              console.log(`Issue already exists for this workflow failure: #${duplicateIssue.number}`);
              return;
            }
            
            // Create the issue body with diagnostic information
            const issueBody = `## Workflow Failure Details
            
**Workflow:** ${workflowName}  
**Run ID:** ${runId}  
**Branch:** ${headBranch}  
**Commit:** ${headSha}  
**Attempt:** ${runAttempt}  
**Started:** ${runStarted}  
**Workflow URL:** ${workflowUrl}

## Description
            
The GitHub Actions workflow "${workflowName}" has failed. This issue was automatically created to track the failure and facilitate debugging.

## Next Steps

- [ ] Review the workflow logs for error details
- [ ] Identify the root cause of the failure
- [ ] Apply necessary fixes
- [ ] Re-run the workflow to verify the fix
- [ ] Close this issue once resolved

## Diagnostic Information

Please check the [workflow run logs](${workflowUrl}) for detailed error information.

---
*This issue was automatically created by the auto-issue-on-failure workflow.*`;

            // Create the issue
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['automated-issue', 'workflow-failure', 'bug'],
              assignees: ['copilot']
            });
            
            console.log(`Created issue #${issue.data.number} for workflow failure`);