# Jekyll site CI - DISABLED to avoid conflicts with GitHub Pages deployment
# This workflow is disabled to prevent conflicts with the main GitHub Pages Jekyll deployment
# Enable this only if you need custom Jekyll builds outside of GitHub Pages

# name: Jekyll site CI
# 
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
# 
# jobs:
#   build:
# 
#     runs-on: ubuntu-latest
# 
#     steps:
#     - uses: actions/checkout@v4
#     - name: Build the site in the jekyll/builder container
#       run: |
#         docker run \
#         -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
#         jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
